import LocalizedStrings from 'localized-strings';

const strings = new LocalizedStrings({
  en: {
    hello: 'hello {0}!',
    welcome: 'welcome!',
    checkVisited: 'have you visited this smart store earlier?',
    nextStep: 'Next Step',
    prevStep: 'Prev Step',
    confirm: 'Confirm',
    info: 'info',
    lastCollection: 'Did you see our lastest collection?',
    download1: 'download our mobile app!',
    download2: 'go to {0} in your mobile browser',
    download3: 'or scan the qr code below!',
    step1: 'step 1',
    step2: 'step 2',
    step3: 'stpe 3',
    createAccount: 'create accoount',
    terms: 'Terms & Conditions',
    back: 'back',
    next: 'next',
    thanks: 'Thank you for signing up!',
    logOrSign: 'log in or sign up',
    inMobile: 'in mobile app',
    whenFinished: 'when finished',
    tapOnBelow: 'tap on {0} below',
    more: 'more',
  },
  ch: {
    hello: '你好 {0}!',
    welcome: '欢迎！',
    checkVisited: '你之前来过这家智能商店吗？',
    nextStep: '下一步',
    prevStep: '上一步',
    confirm: '确认',
    info: '更多信息',
    lastCollection: '你看过我们最新的珍藏吗？',
    download1: '下载我们的手机APP！',
    download2: '在手机浏览器上输入网址：{0}',
    download3: '或者扫描下方二维码！',
    step1: '第一步',
    step2: '第二步',
    step3: '第三步',
    createAccount: '创建账户',
    terms: '条款和条件',
    back: '上一步',
    next: '下一步',
    thanks: '感谢您的注册！',
    logOrSign: '登录或注册',
    inMobile: '在手机app中',
    whenFinished: '当完成后',
    tapOnBelow: '点击下面的{0}',
    more: '更多',
  },
});

export default strings;
